### ISSUE TITLE
blastn: 2.6.0+ and 2.9.0+

### ISSUE THREAD

**Issue by Adelaam** [enormandeau/ncbi_blast_tutorial#1]
Hello,

I am trying to install 2.9.0 version on my ubuntu but still appears the old version installed 2.6.0. How Can I remove the old version to work with the new one?

Thank you!

**Comment by enormandeau** [comment]
Hi Adelaam. I'm just back from vacation but unfortunately, I do not have time to do software installation support. Please find someone around you that can help or look for info online.

Take care
