### ISSUE TITLE
does not match input format type, default input type is FASTA

### ISSUE THREAD

**Issue by katievigil** [enormandeau/ncbi_blast_tutorial#3]
Hi I am getting this error when trying to use the makeblastdb?

makeblastdb -in /lustre/project/taw/kvigil/Reference/viral.1.protein.faa.gz -dbtype prot

Building a new DB, current time: 10/27/2023 10:27:07
New DB name:   /lustre/project/taw/kvigil/Reference/viral.1.protein.faa.gz
New DB title:  /lustre/project/taw/kvigil/Reference/viral.1.protein.faa.gz
Sequence type: Protein
Keep MBits: T
Maximum file size: 1000000000B
BLAST options error: /lustre/project/taw/kvigil/Reference/viral.1.protein.faa.gz does not match input format type, default input type is FASTA

**Comment by enormandeau** [comment]
Hi. Your database needs to be a fasta file but the one you are passing to it is compressed with gzip. You need to gunzip it first.
