### ISSUE TITLE
makeblastdb error "BLAST Database error: No alias or index file found for nucleotide database"

### ISSUE THREAD

**Issue by santataRU** [enormandeau/ncbi_blast_tutorial#4]
I run `makeblastdb  -in test3.fasta -title reference -dbtype nucl -out Data_test3` but got an error at the end as below:

Building a new DB, current time: 11/04/2023 09:06:17
New DB name:   /Users/xiaolei/Downloads/Peng Zhang/BPHunter_fastq2BP_test/Data_test3
New DB title:  reference
Sequence type: Nucleotide
Deleted existing Nucleotide BLAST database named /Users/xiaolei/Downloads/Peng Zhang/BPHunter_fastq2BP_test/Data_test3
Keep MBits: T
Maximum file size: 3000000000B
Adding sequences from FASTA; added 1 sequences in 0.000292778 seconds.

BLAST Database error: No alias or index file found for nucleotide database [/Users/xiaolei/Downloads/Peng] in search path [/Users/xiaolei/Downloads/Peng Zhang/BPHunter_fastq2BP_test::]

Is there a way to fix this issue?

Thanks,
Xiao

**Comment by enormandeau** [comment]
Hi Xiao,

I did a google search but I don't know why you hit that problem.

Good luck,

Eric

**Comment by santataRU** [comment]
Thank you Eric!
